apiVersion: v1
kind: ServiceAccount
metadata:
  name: gopher-operator-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: gopher-operator-cluster-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods/proxy"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["lostinbrittany.dev"] # "" indicates the core API group
    resources:
      ["gopherapis"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: gopher-operator-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: gopher-operator-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: gopher-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io